### ISSUE TITLE
Incorrect node version requirement

### ISSUE THREAD

**Issue by SuperOl3g** [princed/postcss-modules-values-replace#25]
In fact plugin requires [Node 7.5+](https://node.green/#ES2017-features-async-functions) becouse of `async` functions.

In my case built have falled with Node 6.11.4
<details>
<summary>Error text</summary>
<br>

 ```
/opt/teamcity-agent/work/1942dc01ed884f70/node_modules/postcss-modules-values-replace/index.js:72
[16:10:27][Step 3/4] const walk = async (requiredDefinitions, walkFile, root, result) => {
[16:10:27][Step 3/4]                    ^
[16:10:27][Step 3/4] 
[16:10:27][Step 3/4] SyntaxError: Unexpected token (
[16:10:27][Step 3/4]     at createScript (vm.js:56:10)
[16:10:27][Step 3/4]     at Object.runInThisContext (vm.js:97:10)
[16:10:27][Step 3/4]     at Module._compile (module.js:542:28)
[16:10:27][Step 3/4]     at Object.Module._extensions..js (module.js:579:10)
[16:10:27][Step 3/4]     at Module.load (module.js:487:32)
[16:10:27][Step 3/4]     at tryModuleLoad (module.js:446:12)
[16:10:27][Step 3/4]     at Function.Module._load (module.js:438:3)
[16:10:27][Step 3/4]     at Module.require (module.js:497:17)
[16:10:27][Step 3/4]     at require (internal/module.js:20:19)
[16:10:27][Step 3/4]     at module.exports (/opt/teamcity-agent/work/1942dc01ed884f70/webpack/postcss.config.js:34:9)
[16:10:27][Step 3/4]     at Object.<anonymous> (/opt/teamcity-agent/work/1942dc01ed884f70/.storybook/webpack.config.js:125:26)
[16:10:27][Step 3/4]     at Module._compile (module.js:570:32)
[16:10:27][Step 3/4]     at Object.Module._extensions..js (module.js:579:10)
[16:10:27][Step 3/4]     at Module.load (module.js:487:32)
[16:10:27][Step 3/4]     at tryModuleLoad (module.js:446:12)
[16:10:27][Step 3/4]     at Function.Module._load (module.js:438:3)
[16:10:27][Step 3/4]     at Module.require (module.js:497:17)
[16:10:27][Step 3/4]     at require (internal/module.js:20:19)
[16:10:27][Step 3/4]     at exports.default (/opt/teamcity-agent/work/1942dc01ed884f70/node_modules/@storybook/react/dist/server/config.js:57:22)
[16:10:27][Step 3/4]     at buildStatic (/opt/teamcity-agent/work/1942dc01ed884f70/node_modules/@storybook/core/dist/server/build-static.js:77:16)
[16:10:27][Step 3/4]     at Object.<anonymous> (/opt/teamcity-agent/work/1942dc01ed884f70/node_modules/@storybook/react/dist/server/build.js:23:25)
[16:10:27][Step 3/4]     at Module._compile (module.js:570:32)
[16:10:27][Step 3/4] script exit code: 1
```

**Comment by princed** [comment]
Happy to accept a PR with a compilation step, see https://github.com/princed/postcss-modules-values-replace/pull/26#issuecomment-402467062

**Comment by princed** [comment]
Closing this one due to inactivity.
No, I'm not a 🤖

**Comment by kumarharsh** [comment]
I guess you can just drop node 6 now (it goes out of maintenance in April - https://nodejs.org/en/about/releases/)

**Comment by princed** [comment]
I don't think it's actually supported 😃
